### ISSUE TITLE
Adjusting benchmarks.

### ISSUE THREAD

**Issue by rdebath** [birb007/bfasm#1]
I suggest you use a benchmark that stops to count your IPS so you don't get the extra cost of counting the instructions as you go. Perhaps the Mandelbrot.b program that runs in exactly 10,521,107,970 instructions including 6240 print instructions.

http://esoteric.sange.fi/brainfuck/utils/mandelbrot/

Another; this alphabet printer, is 671,105,765 instructions.
``` bf
>++++++++[>+++>>>++++++++<<<<-]>++<<
+[>>>[>>]<[[>>+<<-]>>>+.[>>+<<-]<-[<<]]>+<<[-<<]<]>+>>[-<<]<+++++++++.
```

And 5,368,726,239 instructions.
``` bf
>>>>>>>+++++[>+++++<-]>+>>++++++++[>++++++++<-]<<<<<<<<<<
+[>>>[>>]<[[>>+<<-]>>>+.[>>+<<-]<-[<<]]>+<<[-<<]<]>+>>[-<<]<+++++++++.
```

**Comment by b-irb** [comment]
I will update the benchmarks to use a finite set of instructions to reduce the bench-marking noise. I only considered reducing the initialisation code by increasing the iteration count. However, the extra branch and instruction overhead from the benchmarking stub itself will introduce noise. This was confirmed after testing different snippets and observing a significantly smaller branch miss-predict (~50%). Thank you for the suggestion.
